SELECT * FROM (
SELECT TESTID,BATCHNUMBER,PKGLOT,BLISTERLOT,PRODUCT,FORMULATIONID,CUSTOMER,
    RECEIVEDDATE AS DATERECEIVED, FINISHEDDATE AS DATEFINISHED,
    REQUESTSTATUS,
        AVG(CASE WHEN (PKGLOT IS NOT NULL AND UPPER(TESTGROUP)='MICRO') THEN TESTSTATUS END)
            OVER (PARTITION BY BATCHNUMBER,PKGLOT ORDER BY PKGLOT NULLS FIRST) AS PKGLOT_TESTSTATUS,
        AVG(CASE WHEN (BLISTERLOT IS NOT NULL AND UPPER(TESTGROUP)='MICRO') THEN TESTSTATUS END)
            OVER (PARTITION BY BATCHNUMBER,BLISTERLOT ORDER BY BLISTERLOT NULLS FIRST) AS BLISTERLOT_TESTSTATUS,
        AVG(CASE WHEN (PKGLOT IS NULL AND BLISTERLOT IS NULL) THEN TESTSTATUS END)
            OVER (PARTITION BY BATCHNUMBER ORDER BY PKGLOT NULLS FIRST) AS OTHER_TESTSTATUS,
        SUM(CASE WHEN (UPPER(TRIM(TESTID))='COA REPORT') THEN 1 ELSE 0 END)
            OVER (PARTITION BY BATCHNUMBER,PKGLOT,BLISTERLOT ORDER BY PKGLOT,BLISTERLOT NULLS FIRST) AS HAS_COFA
FROM
    (SELECT
         TR.REQUESTID,
         TR.STATUS AS REQUESTSTATUS,
         T.TESTID,
         T.STATUS AS TESTSTATUS,
         T.TESTGROUP,
         T.FINISHEDDATE,
         P.BATCHNUMBER,
         P.GENERIC01  AS PKGLOT,
         P.GENERIC04  AS BLISTERLOT,
         P.PRODUCT,
         P.FORMULATIONID
         P.GENERIC02  AS CUSTOMER,
         P.RECEIVEDDATE
    FROM
         TESTREQUEST TR,
         TEST T,
         REQUESTSAMPLE RS,
         PHYSICALSAMPLE P
    WHERE TR.REQUESTGUID = T.REQUESTGUID
        AND TR.REQUESTGUID = RS.REQUESTGUID
        AND RS.SAMPLEGUID = P.SAMPLEGUID
        AND TR.STATUS <> 5000 AND TR.DELETION <> 'Y'
        AND T.STATUS <> 5000 AND T.DELETION <> 'Y'
        AND P.DELETION <> 'Y'
    UNION ALL
    SELECT
         TR.REQUESTID,
         TR.STATUS AS REQUESTSTATUS,
         T.TESTID,
         T.STATUS AS TESTSTATUS,
         T.TESTGROUP,
         T.FINISHEDDATE,
         P.BATCHNUMBER,
         P.GENERIC01  AS PKGLOT,
         P.GENERIC04  AS BLISTERLOT,
         P.PRODUCT,
         P.FORMULATIONID
         P.GENERIC02  AS CUSTOMER,
         P.RECEIVEDDATE
    FROM
         TESTREQUEST TR,
         TEST T,
         TESTSAMPLE TS,
         PHYSICALSAMPLE P
    WHERE TR.REQUESTGUID = T.REQUESTGUID
        AND T.TESTGUID = TS.TESTGUID
        AND TS.SAMPLEGUID = P.SAMPLEGUID
        AND TR.STATUS <> 5000 AND TR.DELETION <> 'Y'
        AND T.STATUS <> 5000 AND T.DELETION <> 'Y'
        AND P.DELETION <> 'Y'
    )
)
WHERE REQUESTSTATUS=2000
AND (PKGLOT_TESTSTATUS=1000 OR BLISTERLOT_TESTSTATUS=1000)
AND (OTHER_TESTSTATUS=1000 OR OTHER_TESTSTATUS IS NULL)
AND HAS_COFA=0
AND TESTID='Microbiological'
ORDER BY
  	CASE
	WHEN $P{PARAM_SORT}= 'Batch' THEN BATCHNUMBER
	WHEN $P{PARAM_SORT}= 'Date Received' THEN DATERECEIVED
	WHEN $P{PARAM_SORT}= 'Date Finished' THEN DATEFINISHED
	WHEN $P{PARAM_SORT}= 'Customer' THEN CUSTOMER
	WHEN $P{PARAM_SORT}= 'Product' THEN PRODUCT
	ELSE BATCHNUMBER
	END